### ISSUE TITLE
fs.SyncWriteStream reached end of life

### ISSUE THREAD

**Issue by maksimovicdanijel** [pinojs/pino-clf#2]
Hi,

when using `pino-clf` and trying to save to a file there is an error that SyncWriteStream is not a constructor. Possible solution is to use https://www.npmjs.com/package/syncwritestream which is a drop-in replacement for this function. 

@mcollina Do you maybe have a better idea how to solve this issue?

**Comment by mcollina** [comment]
I think https://github.com/pinojs/pino-toke/blob/master/stdio.js needs to be updated. I don't really know how, I would just aim to make the tests pass

cc @davidmarkclements

**Comment by mcollina** [comment]
https://www.npmjs.com/package/sonic-boom is what we use in pino.

**Comment by davidmarkclements** [comment]
should be closed from https://github.com/pinojs/pino-toke/commit/2d22b4fdfd0dbdb12c2f6424196d120fe05fcef5

it's a patch, reinstall and you should be good.
